python3 main.py \
    --batch_size=128 \
    --STN \
    --mask \
    --gradient \
    --content \
    --vis_dir=CCTB_CP_Loss_4srb_128hd_bsr_sync \
    --nonlocal_type transformer \
    --srb 4 \
    --config_path ../ckpt/CCTB_CP_Loss_4srb_128hd_bsr_sync/ \
    --hd_u 64
